version: '3.9'

x-common-env: &common-env
  GOPATH: /go
  GOCACHE: /src/.cache/gocache
  MONGO_URL: mongodb://mongo:27017/
  MONGO_DATABASE: blog_server
  REDIS_ADDR: redis:6379
  JWT_SECRETKEY: D*G-KaPdSgVkYp3s6v9y$B&E)H+MbQeT

x-common-build: &common-build
  image: justin0u0/golang-protoc:protoc-3.19.3-golang-1.17
  working_dir: /src
  environment:
    <<: *common-env
  volumes:
  - .:/src
  - ~/go/pkg/mod/cache:/go/pkg/mod/cache

services:
  mongo:
    image: mongo:5
  
  redis:
    image: redis:6.2-alpine
  
  generate:
    <<: *common-build
    command:
    - make
    - generate

  lint:
    image: golangci/golangci-lint:v1.44.2
    working_dir: /src
    environment:
      GOLANGCI_LINT_CACHE: /src/.cache/golangci-lint-cache
    volumes:
    - .:/src
    command:
    - make
    - lint

  build:
    <<: *common-build
    command:
    - make
    - build
  
  image:
    image: tsw303005/blog-server:latest
    build:
      context: .
    environment:
      <<: *common-env

  api:
    image: tsw303005/blog-server:latest
    environment:
      <<: *common-env
    command:
    - /cmd
    - api
    - api
    depends_on:
    - mongo

  gateway:
    image: tsw303005/blog-server:latest
    environment:
      GRPC_SERVER_ADDR: api:8081
      <<: *common-env
    command:
    - /cmd
    - api
    - gateway
    depends_on:
    - mongo
    - api
    ports:
    - 8001:8080

  file:
    image: tsw303005/blog-server:latest
    environment:
      <<: *common-env
    command:
    - /cmd
    - file
    ports:
    - 8082:8080

  # nginx:
  #   image: nginx:stable
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 8008:8008
  #   depends_on:
  #     - file
  #     - gateway
