name: CI

on: push

jobs:
  # run linter
  lint:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.44.2

  # build image
  build:
    runs-on: ubuntu-20.04
    needs:
    - lint
    permissions:
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
        
    - name: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-gocache-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-gocache-

    - name: build
      run: make build

    - name: login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v1

    - name: set image name
      run: |
        echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> ${{ github.env }}

    - name: docker build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ github.sha }}
